language: python

python:
  - "3.6"

before_install:
  - "pip install -U pip"
install:
  - pipenv install
  - pip install -r requirements.txt

script:
  - coverage run --source=. manage.py test && coverage report && coverage html
after_success:
  - codecov
