language: python

python:
  - "3.6"

before_install:
  - "pip install -U pip"
install:
  - pipenv install
  - pip install -r requirements.txt
env:
  global:
    - CC_TEST_REPORTER_ID=ABC123

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run --source=. manage.py test && coverage report && coverage html
after_success:
  - codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
