version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 4d80a81a5bebd0ce7683a8e47bd35a593aafa46726b09456ebca2f99b44d4d0d
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
      - run:
          name: Setup Code Climate test-reporter
          command: |
          # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

workflows:
  main:
    jobs:
      - build-and-test
