# Generated by Django 3.1.7 on 2021-03-25 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('5e841999-4ad3-45af-be0e-63725f911d2d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
