# Generated by Django 3.1.7 on 2021-04-12 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210325_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('d0a40804-6d35-4444-be79-1ceb41a73fff'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default='+254714568338', max_length=300, null=True),
        ),
    ]
